### ISSUE TITLE
mix coveralls.github yields ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1 

### ISSUE THREAD

**Issue by felipelincoln** [parroty/excoveralls#229]
I have a docker container with env variable `MIX_ENV=test` and in my github action I run
```
docker exec -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} test_container mix coveralls.github
```
And this is what I get

```
Run docker exec -e GITHUB_TOKEN=*** test_container mix coveralls.github
Compiling 24 files (.ex)
Generated prequest app
.................................................

Finished in 0.9 seconds
49 tests, 0 failures

Randomized with seed 655422
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1    
    
    The following arguments were given to IO.chardata_to_string/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 2 out of 2):
    
        def chardata_to_string(+string+) when -is_binary(string)-
        def chardata_to_string(+list+) when -is_list(list)-
    
    (elixir 1.10.4) lib/io.ex:572: IO.chardata_to_string/1
    (elixir 1.10.4) lib/file.ex:339: File.read/1
    (elixir 1.10.4) lib/file.ex:348: File.read!/1
    (excoveralls 0.13.1) lib/excoveralls/github.ex:84: ExCoveralls.Github.event_info/0
    (excoveralls 0.13.1) lib/excoveralls/github.ex:56: ExCoveralls.Github.get_committer_name/0
    (excoveralls 0.13.1) lib/excoveralls/github.ex:93: ExCoveralls.Github.git_info/0
    (excoveralls 0.13.1) lib/excoveralls/github.ex:25: ExCoveralls.Github.generate_json/2
    (excoveralls 0.13.1) lib/excoveralls/github.ex:8: ExCoveralls.Github.execute/2
    (mix 1.10.4) lib/mix/tasks/test.ex:484: Mix.Tasks.Test.do_run/3
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.4) lib/mix/task.ex:364: Mix.Task.run_alias/3
    (mix 1.10.4) lib/mix/task.ex:292: Mix.Task.run/2
     (excoveralls 0.13.1) lib/mix/tasks.ex:54: Mix.Tasks.Coveralls.do_run/2
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.4) lib/mix/cli.ex:82: Mix.CLI.run_task/2
    (elixir 1.10.4) lib/code.ex:926: Code.require_file/2
##[error]Process completed with exit code 1.
```

**Comment by felipelincoln** [comment]
I suspect it is searching for the github built-in env variables, I will test it and return here

**Comment by felipelincoln** [comment]
In a docker container it obviously doesn't have the github action default environment variables. That's why it doesn't support docker container. I will see what I can do.

**Comment by felipelincoln** [comment]
I got a solution to make `mix coveralls.github` work inside a docker container. All we need to do is to pass the following github action default environment variables:

* `GITHUB_SHA`
* `GITHUB_REF`
* `GITHUB_EVENT_PATH`
* `GITHUB_EVENT_NAME`

And also copy the `event.json` from the github filesystem to the container.  
This is a working example:

```yml
name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose services
        run: |
          docker-compose run --name test_container \
          -e MIX_ENV=test \
          -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          -e GITHUB_SHA=$GITHUB_SHA \
          -e GITHUB_REF=$GITHUB_REF \
          -e GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json \
          -e GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME \
          -d web /bin/sh
      - name: Copy github's event.json to container
        run: |
          docker exec test_container mkdir -p /home/runner/work/_temp/_github_workflow/
          docker cp $GITHUB_EVENT_PATH test_container:/home/runner/work/_temp/_github_workflow/

      - name: Run mix coveralls.github
        run: docker exec test_container mix coveralls.github
```
